export const featureData = {
  core: [
    {
      Feature: "Minutes per month",
      Free: "75 mins",
      Essential: "200 - 500 mins",
      Growth: "200 - 1000 mins",
      Custom: "400 - 1000 mins",
    },
    {
      Feature: "Render Quality",
      Free: "720p",
      Essential: "1080p",
      Growth: "1080p",
      Custom: "4K",
    },
    {
      Feature: "Import with Youtube or Computer Upload",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Import with Integrations (Drive, Dropbox, Box)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Al Subtitles (Captions)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Multi-lingual feature",
      Free: "yes",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
  ],
  brandKit: [
    {
      Feature: "Custom Brand Templates",
      Free: "no",
      Essential: "no",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Render Quality",
      Free: "720p",
      Essential: "1080p",
      Growth: "1080p",
      Custom: "4K",
    },
    {
      Feature: "Import with Youtube or Computer Upload",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Import with Integrations (Drive, Dropbox, Box)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Al Subtitles (Captions)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Multi-lingual feature",
      Free: "yes",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
  ],
  social: [
    {
      Feature: "Social Media Publishing",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Render Quality",
      Free: "720p",
      Essential: "1080p",
      Growth: "1080p",
      Custom: "4K",
    },
    {
      Feature: "Import with Youtube or Computer Upload",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Import with Integrations (Drive, Dropbox, Box)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Al Subtitles (Captions)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Multi-lingual feature",
      Free: "yes",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
  ],
  metaData: [
    {
      Feature: "Video transcript",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Render Quality",
      Free: "720p",
      Essential: "1080p",
      Growth: "1080p",
      Custom: "4K",
    },
    {
      Feature: "Import with Youtube or Computer Upload",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Import with Integrations (Drive, Dropbox, Box)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Al Subtitles (Captions)",
      Free: "no",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
    {
      Feature: "Multi-lingual feature",
      Free: "yes",
      Essential: "yes",
      Growth: "yes",
      Custom: "yes",
    },
  ],
};
